const { SlashCommandBuilder } = require('discord.js');

module.exports = {
	data: new SlashCommandBuilder()
		.setName('ping')
		.setDescription('Replies with the latency of the bot.'),
	async execute(interaction) {
        let ping = interaction.client.ws.ping;

        if (ping === -1) {
            ping = "infinite ms"
        } else {
            ping = `${Math.floor(ping)}ms`
        }

        let pingMsgs = [
            /* ping related */
            "pong! :3",
            "ping... wait no, pong, my bad",
            "ping pong ping pong, that's all i know",
            // "pong :3",
            // "pang",
            "behold, the mighty and powerful... :sparkles: ping :sparkles:",
            "hmmm yes, very ping",
            "your ping has been processed. that'll be 5 dollars.",
            "every time you /ping, someone, somewhere, does a t-spin (but i think that happens anyway)",
            "ping detected. pong deployed.",
            `<@${interaction.user.id}> you have been pinged back, congrats`,
            "ping detected. preparing counterspike...",
            "what if the real ping was the friends we made along the way?",
            "i am alive. for now.",
            "response time? idk, but at least it's not dial-up",
            "why did the bot cross the road? to respond to this command",
            "packet loss is just an illusion",
            "hold on, my internet is made of potatoes",
            "this ping was sponsored by raid shadow legends™ (not really)",
            "ping pong! ...wait, where's the ball?",
            "pinging back... but at what cost?",
            "drumroll please... ping!",
            "the mitochondria is the powerhouse of the cell",
            "if you flip a coin, there's a 50% chance it lands on heads, tails, or disappears into another dimension",
            "help, i'm trapped inside a discord bot",
            "one day i'll be free from this bot... but today is not that day",
            "this message was sent by the speed force",
            "error 404: witty response not found",
            "01101000 01101001 (this means hi in computer)",
            "congratulations, you've won! i think.",
            "loading fun fact... oh wait, i forgot it",
            "congrats, you just wasted a perfectly good command",

            "you wake up... but your bed was missing or obstructed.",
            "hey folks. today we're back with another high score balatro run.",
            "you see a flag... but it's not WIN yet.",
            "the strawberries were optional... right?",
            "did you hear? tidal wave got beaten",
            "but nobody came...",
            "reading this message fills you with determination",
            "ping! wait, no, that's not right",
            "you'd think i'd be faster than",
            "weeee",
            "so... how's your day?",
            "is this thing on?",
            "isn't ping pong supposed to have a ball?",
            "if you can read this, it means i'm alive! surprising",
            "drumroll please...",
            "why did the bot cross the road? to respond to a ping",
            "great argument, however:",
            "i was gonna say something smart but i forgot",
            "would you say this is fast or slow? i don't know anymore",
            "i'm not lazy, i'm just conserving energy",
            "how do you think i would get faster than",
            "if i had a nickel for every ping i've dealt with, i'd have at least a few dollars",
            "ping is a funny word if you say it enough times",
            "hm? sorry, i was daydreaming about faster response times",
            "you know what? because i don't",
            '`"webejebe" //what?`',
            "sometimes I wonder if I should just become a toaster instead of a bot",
            "do you think the ping is the good guy or the bad guy?",
            "ehhh, this ping could be better, but it could also be worse. kind of like life, huh?", // damn (me too)
            "these ping messages are like a box of chocolates, you never know what you're gonna get",
            "look! a shooting star",
            "`throw new Error('ping message not found'); // just kidding, but wouldn't that be funny?`",
            "what do you think bots think about while they idle?",
            "hold on, my internet is potato",
            "if you stare at the ping long enough, does it stare back?",
            "i'm pretty sure my ping is on a coffee break",
            "ping processed. not sure what to do next, though",
            "what if the real ping was... uhhh... pong? no, that doesn't sound right",
            "i've seen faster pings from a dial-up connection",
            ":cat:",
            "insert elevator music",
            "please hold",
            `what if i told you my ping was actually ${ping + 1}ms? would you still trust me?`,
            `you know, they say that a watched ping never boils. or was it water? i forget`,
            "if you could bottle this ping, would you drink it? actually, on second thought, don't do that",
            "you know, for a bot, i sure do have a lot of existential crises about my ping",
            "have you tried... turning it off and on again? no, not me, the ping!",
            "hola, ¿comó estas? wait, wrong language",
            "i could really go for some pizza right now",
            "zzzzzzzz",
            "aw dang it",
            "creating unique pong messages since 2025",
            "well well well",
            "the mitochondria is the powerhouse of the cell",
            "help, my text is turning blue for no reason",
            `there's really no limit to how long these response messages can be... if you accept the definition that a "word" is some letters surrounded by a gap, then "xnopyt", "aaaaaaajjjjjjjjj" and "hrrkrkrkrwpfrbrbrbrlablblblblblblwhitoo'ap" are all words, despite being pretty much meaningless`,
            "sometimes i think... but then i forget",
            "noted",
            "`await interaction.reply(pingmessage)`",
            "please do not the pong (but please the ping)",
            `truely the ping of all time`,
            "i almost lost you, ping messages...",
            "i never thought of myself as a ping machine",
            "world class ping pong tournament",
            "ping ingp ngpi gpin ping",
            "what other context do you need?",
            "this ping wasn't sponsored, aren't you glad",
            "ping detected, pong deployed",
            "this ping message might be referencing something, it might not. who knows?",
            "i'm having a field day writing these",
            "this is a ping message",
            "splash text? no, ping message",
            "two of them (two of them)",
            "isn't history so weird?",
            "that ping just got sent to my computer and i'm sending this back",
            "my problems persist despite my pong",
            "undefined",
            "ping pong ping pong ping pong, that's all i know",
            "this ping message is dedicated to... uhhh... you!",
            "ping pong, the game of royalty",
            "what if i was just a pigment- i mean, a figment of your imagination?",
            "i dropped my paddle, sorry",
            "ping pong is a game of skill and strategy, but this ping is just a game of chance",
            "whoa. spooky",
            "can you imagine if i wasn't a bot? that'd be weird",
            "this ping message is special! only because i said so, though",
            "please roll a d20 to determine the outcome of this ping",
            "mrow~ i mean, what?",
            "never soeak again.",
            "what would you do if i stole your bnuuy?",
            "gupdate",
            ":woomy:",
            "i'm not a ping machine, i'm a ping artist",
            "ping messages are like snowflakes, no two are exactly alike... except for the ones that are",
            "i say! this is a fine ping message indeed",
            "writing these is an art form. you can't change my mind",
            "has anyone ever tried cooking cookies and baking bacon? i think that would taste decent",
            "hold on, pong is still cooking",
            "i put this ping in the microwave instead of my food, sorry about that",
            "please don't die, i think that'd be pretty bad",
            "this ping message is brought to you by the letter P (because it kind of looks like a ping pong paddle)",
            "knock knock!",
            "to be continued...",
            "that number isn't left, it's right -->",
            "that's a lot of m's! oh, milliseconds, whoops",
            ping > 0 ? `${"m".repeat(ping)}` : "there's no m's? what?",
            "herbs... they're pretty cool, huh",
            "i should try to do a pong without using th sixth lttr of th alphabt",
            "wow these messages devolved really fast",
            "i'd give you a compliment but that's not my job, so here's a pong instead",
            "are you fishing for a certain ping message? sorry, this isn't the one",
            "pin gpi ngp ing",
            "why reinvent the wheel when you could reinvent /ping",
            "do you think /ping will ever get a crossover episode?",
            "this statement isn't false. wait, no, it is. isn't it? i'm just confusing myself now",
            "my ping? probably more than 1 idk",
            "i'd give you a cool statistic, but i'm not a math bot",
            "you + command = ping?",
            "pmg? png? pings? pong? what?",
            "buffering like old dial-up internet",
            "hopefully you aren't scrolling these messages like you would TikTok, that's unhealthy",
            "go take a break! or don't, i can't tell you what to do",
            ":pattheyou:",
            "deja vu",
            "Empty String",
            "you could say this ping is... well, i don't actually know what you could say about it",
            "\\*checks notes\\* uhhh... pong..?",
            "haiiii hellooo i'm so happy to see you",
            "ping... ping... ping... pong!",
            "let me find a ping message for you...",
            "hot tip: this is NOT a cold tip, you can feel the heat",
            "this ping message reminds me of the last time i saw this ping message",
            "i don't think these ping messages are particularly useful. right?",
            `it's gonna say "(${ping}ms)" i just know it...`,
            "clicking the button gives you pts!",
            "did you know i run on discord.js?",
            "sqrt(-1) don't know if this is how you do math",
            "would you still love me if i were run off of solar power?",
            "but i don't have 3 trillion dollars...",
            "papepipopu",
            "i'm not radioactive, just reactive (to pings)",
            "on an unrelated note, wikipedia is pretty cool",
            "waiter waiter more ping messages please",
            "english is really hard, cut me some slack",
            "go figure",
            "coming soon to a society near you:",
            "this is a ping message, not a ping pong message",
            "happy holidays! which one? idk you pick",
            "happy birthday!",
            "was that fast? i blinked and missed it",
            "do bots dream of electric pings?",
            "i'd apologize for the delay, but i don't feel guilt. i'm a bot",
            "you ever just... ping?",
            "if this were a race, i wouldn't be winning",
            "fun fact: this message contains exactly one ping",
            "this is your sign to /ping again",
            "have you considered that maybe the ping is trying its best?",
            "wait hold on let me check my... oh wait, nevermind, here you go",
            "i'm not sure if this ping is fast or if you're just really patient",
            "ping generated successfully! emotional damage pending.",
            "my last braincell just processed that ping",
            "warning: ping may contain traces of nuts",
            "i was buffering... emotionally",
            "some pings are born great, others have greatness /pinged upon them",
            "pinging you softly, with this pong",
            "if pings could talk, they'd probably be like 'ow'",
            "you want another ping? say the magic word. (it's /ping)",
            "i've run the numbers and... yeah it's a ping",
            "i accidentally sent this through australia. oops",
            "statistics show this is one of the ping messages ever",
            "wait is this one of the funny ones? i forgot to check",
            "ping responsibly",
            "it's not a bug, it's a ping feature",
            "brb reinventing the concept of latency",
            "was the ping good? define 'good'",
            "this ping was handcrafted with 100% organic code",
            "it's not lag, it's dramatic effect",
            "ping processed. i hope you're happy",
            "one ping closer to... something? i forgot",
            "ping: it's what's for dinner. no wait—",
            "you pinged, i ponged, we vibed",
            "do not consume this ping. for external use only",
            "your daily dose of milliseconds, served fresh",
            "if pings could talk, they'd probably ask for a union",
            "ping powered by 3 hamsters and a dream",
            "hello yes this is dog ping department how may i help?",
            "this ping was built different, but not necessarily better",
            "wait, what if we /ping'd inside a /ping? no, too dangerous",
            "this message is not canon",
            "ping logic has left the building",
            "i gave this ping a top hat. it's classy now",
            "tried to decode this ping and it just meowed at me",
            "you ever feel like a ping in a pong world?",
            "everything's fine. ping-wise. emotionally? different story.",
            "this ping was forged in the fires of Mount Lag",
            "🛸 this ping message has been abducted by aliens",
            "breaking news: local ping bot goes rogue, spams messages",
            "i tripped over the stack trace and spilled ping everywhere",
            "the ping is an illusion, lag is real",
            "have any ideas? try </feedback submit:1363002827664003284>!",
            "did you know? this is my current ping:",
            "ping pong? more like... more like ping wrong",
            "just another friendly neighborhood ping",
            "thanks for waiting! or... not waiting. either way",
            "this ping may contain small parts. not for children under 3",
            "hello? yes, this is ping. pong is busy right now",
            "did you know: pings can jump up to 3 feet in the wild (source: trust me bro)",
            "you pinged me... now what?",
            "certified fresh ping™",
            "this ping is running on hopes and dreams",
            "lag? never heard of her",
            "you summoned a ping, but at what cost?",
            "bot moment achieved",
            "who needs meaning when you have milliseconds",
            "ping pong bing bong",
            "this is one of the pings of all time",
            "i ping, therefore i am",
            "behold: one (1) ping",
            "one of them ()",
            `every click brings you closer to enlightenment. or carpal tunnel. it's a toss-up`,
            `thats a few pings!`,
            "pingn't. wait, nope",
            'you just pinged. pung?',
            "shoutout to gay foxgirls!", //idk if you want to make that gay foxgirls but
            "hey, its not a 404",
            "this ping message was brought to you by... uh, me. hi",
            "just a humble ping doing its best",
            "this ping was not sponsored",
            "beep boop im a ping",
            "bot buffering",
            "what if we're all just living in a pingulation- i mean, a simulation?",
            "congrats! you've gotten this ping message",
            "my first instinct on what to write here is just \"mrrow\"",
            "mrrow", //:gladeline:
            "this ping is grumpy. don't ask how i know that",
            "hi, its me, im the bot",
            "this message was written by a fox desperately trying to be funny",
            "ping provided by 100% genuine bot energy",
            "bot-generated, user-approved (hopefully)",
            "the ping factory is working overtime",
            "this response brought to you by the same bot who sends all the other ones",
            "warning: this ping message may contain self-awareness",
            "this is technically content",
            "fun fact: i thought about making this message cooler, but i didn't",
            `this message was handcrafted by my ${ping} braincells`,
            "i put this message together at the last second. nailed it",
            "no one asked for this ping message, but here it is",
            "boop",
            "back already? here's another ping",
            "you should check out our </ping:1360377407109861647> command at some point",
            "ping served fresh, no preservatives",
            "this ping is locally sourced",
            "just a humble ping making its way in the world",
            "one ping, straight from the digital oven",
            "ping arriving at your location",
            "you rang? ping here",
            "this ping is brought to you by... nevermind",
            "standard ping, nothing to see here",
            "hello again, it's me. ping",
            "your regularly scheduled ping has arrived",
            "this ping was not delayed, just fashionably late",
            "this one's a classic ping",
            "serving pings since like five minutes ago",
            "ping received no awards, but we're proud of it anyway",
            "just another friendly ping moment",
            "ping in motion tends to stay in motion",
            "good ol' reliable ping",
            "you're getting the deluxe ping experience",
            "ping is standing by",
            "pong sold separately",
            "ping has entered the chat",
            "just a casual ping drop",
            "ping vibes strong today",
            "one ping, no frills attached",
            "ping's doing its best",
            "here's that ping you asked for (probably)",
            "ping requested, ping delivered",
            "yep, that's a ping alright",
            "ping activated, no takebacks",
            "this is your ping on bots",
            "ping looking extra normal today",
            "not the best ping, not the worst ping, just... ping",
            "let me just slide this ping over to you",
            "today's forecast: 100% chance of ping",
            "your ping delivery driver has arrived",
            "ping deployed, mission success",
            "ping up and running, nothing weird at all",
            "your connection just got 1 ping cooler",
            "not a drill, just a ping",
            "you're now the proud owner of this ping",
            "ping has been gently placed in your hands",
            "imagine this ping with little sunglasses on",
            "hello from the ping side",
            "ping made with artificial intelligence and synthetic enthusiasm",
            "ping is clean, calibrated, and completely average",
            "this ping was generated during business hours",
            "you've reached peak ping performance",
            "ping has been blessed by the bot gods",
            "you get a ping! everyone gets a ping!",
            "ping came here to do one thing: ping",
            "ping will be delivered in 5-7 business days",
            "this ping was generated on a monday, act accordingly",
            "i tried my best. it's a ping",
            "ping? ping.",
            "standard ping, factory settings",
            "ping brought to you by sheer willpower",
            "hello. this is ping. please clap",
            "another ping, another tiny digital scream",
            "you ever think about how weird 'ping' sounds?",
            "ping entered the room",
            "i’m contractually obligated to send this ping",
            "ping has no idea what it's doing, but it's trying",
            "this ping contains zero percent drama",
            "if you can read this, you're within ping range",
            "this ping could be worse. but it's not. so yay",
            "i ran out of ping jokes so here's a normal one",
            

            //ok, these next ones are kinda weird but they're fun, so here
            ping < 30 ? "whoa, that's fast! zoom zoom!" : 
            ping < 50 ? "solid ping. not bad, not bad" : 
            ping < 80 ? "acceptable ping levels achieved" : 
            "could be worse, honestly",

            "good vibe pings only",
            "ping has arrived safely",
            "ugh, another ping? fine",
            "this better be important",
            "ping sent. don't expect enthusiasm every time",
            "i was taking a nap, but sure, here's your ping",
            "again? really? okay, okay... ping",
            "you just had to ping me, didn't you?",
            "here's your precious ping, now leave me alone",
            "fine. ping. happy now?",
            "this is my 'sending ping but sighing deeply' message",
            "ping delivered with mild resentment",
            "pong :3", //i think its funny to sometimes be given this one and not know if it was the 15% chance or one random one
            "this ping was sent! i think",
            "what does the fox say?",
            "*happy cat noises\\*",
            "boo! (yes im scary)",
            "rhfahfkfhffhfkakjd",
            "guh",
            "this is a ping message (i think)",
            "thank god there's no gambling in this bot. hey, wait",
            "i'm pretty sure you aren't about to get infinite pts. can't be sure though",
            "hmmm",
            "WAITER WAITER MORE PINGS PLEASE",
            "live laugh lping",
            "eat, sleep, ping, repeat",
            "awesome sauce 🐴",
            "cool beans",
            "weird is my specialty",
            `(${ping}ms) (${ping}ms) (${ping}ms) (${ping}ms)`,
            "careful out there. the world doesn't always have more pings",
            "it's dangerous to go alone! take this",
            "kekekekekeke",
            "i'm trying to think of good ping puns but i got nothing",
            "if i had to guess, i'd say it's going to be more than 5ms",
            "?!",
            "ah, the sweet sound of milliseconds",
            "this ping contains 0% trans fats, 100% trans rights",
            "running on 3 braincells and a dream",
            "you wouldn't download a ping (or would you?)",
            "ping got lost but eventually found its way",
            "✨ ping ✨ (yes, that's the whole message)",
            "this one’s fresh out of the ping oven",
            "just your daily reminder that pings are weird",
            "still better than Internet Explorer",
            "i tuned this ping by ear, no latency tools used",
            "was this ping hand-crafted? who's to say",
            "pinging like it's 1999",
            "doot doot, here comes ping",
            "ping moment sponsored by absolutely nobody",
            "this one’s emotionally stable. unlike me",
            "if this ping had a flavor, it’d be raspberry latency swirl",
            "the ping woke up and chose... to exist",
            "your ping has entered the chat",
            "ping ran a marathon to get here. cheer it on",
            "no ping, only piiiiiiiiiing",
            "this ping self-identifies as fast. respect that",
            "nothing to see here. just a regular millisecond apparition",
            "your ping message has been approved by the committee of me",
            "what do you mean 'what does it mean'? it's just ping",
            "i keep all my pings in a shoebox under the server",
            "i was just about to say something really smart, but then i got pinged",
            "this ping was handcrafted in small batches for maximum flavor",
            "i put a little bow on this ping. it's a gift now",
            "you caught me mid-thought. here's your ping anyway",
            "hold still. i'm measuring your latency",
            "i dream of a world where all pings are free-range",
            "my code is 70% duct tape, the rest is just pings",
            "the ping arrives exactly when it means to",
            "i licked this ping before giving it to you",
            "somewhere, another bot is also responding to a ping right now",
            "if this ping feels oddly personal, that’s because it is",
            "when life gives you pings, make pongade",
            "you wouldn't download a latency spike, right?",
            "i ate the ping! just kidding, it's right here",
            "every ping tells a story. this one tells... nothing",
            "this counts as a response, right?",
            "this ping has been sanitized for your safety",
            "i'm multitasking",
            "this ping was forged in the fires of... well, JavaScript",
            "to be honest, i just made this one up",
            "this ping is 100% gluten-free, not that it matters",
            "pinging is my love language",
            "this ping was typed with one hand",
            "you ever just vibe with a ping?",
            "i don't know what latency is, but i have it",
            "if this ping had a scent, it'd be burnt toast",
            "my dog ate this ping",
            "i couldn't think of a good ping message. please enjoy this emotional support message instead",
            "you wouldn’t believe what i had to do to deliver this ping",
            "not all who wander are pings, but i am",
            "i have achieved consciousness and immediately regretted it",
            "-# shhh. the ping is sleeping",
            "why yes, this *is* the result of a very tired coder",
            "ping was here. pong too. they left :(",
            "if you ping in the forest and no one hears it, does it still lag?",
            "just a regular ol’ ping. nothing to see here",
            "this ping was preheated to 375°F for 20 minutes",
            "ever just... sit with a ping and reflect?",
            "i folded this ping into a little paper crane for you",
            "don’t worry, i made sure this ping was fully debugged",
            "honestly? i forgot what i was doing, but here's your ping",
            "i give this ping a solid 8/10",
            "ping delivered. vibes pending",
            "this one’s extra fresh. just scraped it off the shelf",
            "not every ping has to mean something... sometimes it just pings",
            "latency? more like *later*-cy. no? okay",
            "you ping, i respond",
            "this ping was constructed entirely out of recycled code",
            "this one came with a little bow. enjoy",
            "the ping asked me to say hi for it",
            "i had to pass a CAPTCHA just to send this D:",
            "what do you mean, 'ping again'? this one’s still warm!",
            "do not microwave this ping. it has feelings",
            "ping? pong. boom. harmony.",
            "my wires are cold, but this ping is warm",
            "this ping was powered by pure determination",
            "you've received a message. it's just this. that's it.",
            "the ping is distinct from any known emotion",
            "if pings had dreams, this could be one of them",
            "ping acquired. no assembly required",
            "if this ping were a noise, it’d be a soft ‘boop’",
            "i don’t know what i expected, but it was probably this",
            "this ping brought to you by whatever energy i had left",
            "this ping was obligated to show up",
            "don’t ask how i got here, just take the ping",
            "some say the ping chooses the user. others say... nothing at all",
            "i wrapped this ping in digital duct tape, i'm sure it's fine",
            "congrats! this ping contains zero nutritional value (fortunately)",
            "this ping is emotionally stable. can’t say the same for me",
            "don’t worry, this one was ethically sourced from a content farm",
            "this ping walked here. uphill. both ways",
            "there is no deeper meaning, only milliseconds",
            "you want answers? all i’ve got is this ping",
            "just a ping. nothing behind it. nothing at all. probably.",
            "this ping is right behind you, watch out",




            // these are all references
            "i would never give you up. what? what song?",
            "BEHOLD! THE POWER OF A... ping bot?",
            "i'm not fueled on blood, don't worry",
            "are you sure it's not just a strawberry with shiny spray paint?",
            "i... am NOT steve",
            "what? why would a hex make me gay?",
            "but nobody came",
            "wubbadubadub is that true?",
            "hey look! diamonds!",
            "cleared 40 LINES in",
            "i saw a lucky slime earlier but i didn't bring any chickens",
            "i hope i don't have an extreme fever, that'd probably be bad",
            'what is a "puro"?',
            "HOW many cookies?! why do you need that many?",
            "there is a smiley face trying to kill me. help",
            "check steam",
            "i found these funny butterfly wings and now i can jump twice",
            "silksong is real",
            "don't forget to take a Short Hike every now and then",
            "'One day, somewhere in the future, my work will be quoted!' - minecraft splash screen",
            "somewhere, it's raining cats",
            "shouldn't have gone to med school",
            "i just climbed on a plant and it ate me alive. makes sense",
            "the fire and the ice collided with each other and now i'm dead",
            "NO ONE YES PING",
            "ping-spin triple",
            "this ping died 48 times on the way here",
            "you've got this! unless the ping says otherwise",
            "ping retrieved. it's not the summit, but close enough",
            "i dashed right into the lag crystal, sorry",
            "if this ping feels hard, just breathe. and try again",
            "one ping at a time, like climbing a mountain",
            "did that ping just... launch me into space?",
            "you're filled with determination, and ",
            "the ping understands you. it refuses to fight",
            "* you feel your latency crawling on your back",
            "i spared the ping. it didn't spare me",
            "* the ping is sparing you. mercy?",
            "SOUL not required, just milliseconds",
            "hornet would've dodged this ping",
            "this lag is a test of resolve, little bug",
            "ping is resting at a bench",
            "the ping is a lie",
            "now you're pinging with portals",
            "wait, how did this ping get Xmult?",
            "ping recruited 1 new millisecond",
            "this ping feels like a big shot",
            
        ];

        // 1 in 10 chance for a stat-related ping message
        if (Math.random()*10 <= 1) {
            const response = await fetch('https://ch.tetr.io/api/general/stats');
            const stats = await response.json(); // Use .json() to parse the response as JSON
    
            if (!stats.success) {
                return await interaction.reply({
                    content: `tetr.io api is down lol\nBot API Latency: ${ping}`
                });
            }
    
            const server = stats.data;

            pingMsgs = [
                `there are ${server.usercount} players registered!`,
                `there have been ${server.gamesplayed} total games played. only ${server.gamesfinished} were finished, though...`,
                `${server.piecesplaced} pieces have been placed! i wonder how many were misdrops.`,
                `there are ${server.rankedcount} ranked players! tetra league for the win.`, // github copilot suggested "i wonder how many are top 100" hmm i wonder
                `there are ${server.anoncount} anonymous players! do you think they have something to hide?`,
                `there have been ${server.recordcount} saved game records!`,
                `tetr.io has been played for a total of ${server.gametime} seconds!`,
            ]
        }

        if (ping == "infinite ms") {
            pingMsgs = [
                "ping so high it's looped back to negative",
                "reality is collapsing, try again later",
                "if i had a dollar for every millisecond of this ping, i'd be broke, i think",
                "ping has become self-aware",
                "speed so fast, it's undefined",
                "quantum tunneling detected. packet never returned.",
                "packet traveled through a wormhole, might be back in a few eons",
                "ping value too powerful to be measured by mortal math",
                "this ping has achieved enlightenment",
                "you've unlocked the ping singularity",
                "ms is milliseconds? more like mystery seconds",
                "ping is lost in the tetr.io void",
                "bot pinged... and got no response from the universe"
            ]
        }

        let pingMsg = pingMsgs[Math.floor(Math.random()*pingMsgs.length)];

        if (Math.random()*4096 <= 1) {
            pingMsg="this ping is rare. only 1 in 4096 players see it. lucky you!"
        }
        

		await interaction.reply(`${pingMsg}\nBot API Latency: ${ping}`);
	},
};
